packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@types/node': 22.15.29
  '@tanstack/router-plugin': ^1.120.13
  '@tanstack/react-router': ^1.120.13
  '@tanstack/router-devtools': ^1.120.13
  '@tanstack/react-start': ^1.120.13
  '@tanstack/react-router-devtools': ^1.120.13
  '@tailwindcss/cli': ^4.1.8
  '@tailwindcss/postcss': ^4.1.8
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.0
  eslint: ^9.28.0
  typescript-eslint: ^8.33.0
  eslint-plugin-react-hooks: ^5.2.0
  '@vitejs/plugin-react': ^4.5.0
  autoprefixer: 10.4.21
  jiti: ^2.4.2
  postcss: ^8.5.4
  react: ^19.1.0
  react-dom: ^19.1.0
  swd-eslint-config: 2.0.2
  prettier: ^3.5.3
  tailwindcss: 4.1.8
  turbo: ^2.5.4
  typescript: 5.8.3
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  '@tanstack/react-query': ^5.79.0
  '@t3-oss/env-core': 0.13.6
  '@tailwindcss/vite': ^4.1.8
  '@tanstack/react-query-devtools': ^5.79.0
  '@tanstack/react-router-with-query': ^1.120.13
  '@trpc/client': ^11.2.0
  '@trpc/server': ^11.2.0
  '@trpc/tanstack-react-query': ^11.2.0
  superjson: ^2.2.2
  vinxi: ^0.5.6
  zod: ^3.25.46
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.3.0
  jsdom: ^26.1.0
  vitest: ^3.1.4
  web-vitals: 5.0.2
  '@tanstack/eslint-config': 0.2.0
  '@radix-ui/react-slot': ^1.2.3
  'tw-animate-css': ^1.3.3
