packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/node': 22.15.29
  '@tanstack/router-plugin': ^1.125.1
  '@tanstack/react-router': ^1.125.1
  '@tanstack/router-devtools': ^1.125.1
  '@tanstack/react-start': ^1.125.1
  '@tanstack/react-router-devtools': ^1.125.1
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/postcss': ^4.1.11
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  eslint: ^9.30.1
  typescript-eslint: ^8.35.1
  eslint-plugin-react-hooks: ^5.2.0
  '@vitejs/plugin-react': ^4.6.0
  autoprefixer: 10.4.21
  jiti: ^2.4.2
  postcss: ^8.5.6
  react: ^19.1.0
  react-dom: ^19.1.0
  swd-eslint-config: 2.1.3
  prettier: ^3.6.2
  tailwindcss: 4.1.11
  turbo: ^2.5.4
  typescript: 5.8.3
  vite: ^7.0.2
  vite-tsconfig-paths: ^5.1.4
  '@tanstack/react-query': ^5.81.5
  '@t3-oss/env-core': 0.13.8
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-query-devtools': ^5.81.5
  '@tanstack/react-router-with-query': ^1.125.1
  '@trpc/client': ^11.4.3
  '@trpc/server': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  superjson: ^2.2.2
  vinxi: ^0.5.8
  zod: ^3.25.74
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.3.0
  jsdom: ^26.1.0
  usehooks-ts: ^3.1.1
  vitest: ^3.2.4
  web-vitals: 5.0.3
  '@radix-ui/react-slot': ^1.2.3
  tw-animate-css: ^1.3.5
